--CREATE DATABASE GNSEACORP
--GO
USE GNSEACORP
GO
CREATE TABLE MENU
(
	MENU_ID		CHAR(2)			NOT NULL,
	TYPE		VARCHAR(2)		NOT NULL,
	PARENT_ID	NVARCHAR(4)		NOT NULL,
	MENU_NAME	NVARCHAR(50)	NOT NULL,
	DESCRIPTION	NVARCHAR(500),
	VALID_FLAG	BIT				DEFAULT 1,
	ADD_USER	NVARCHAR(20)	NOT NULL,
	ADD_DATE	DATETIME		NOT NULL,
	UPDATE_DATE	DATETIME		NOT NULL,
	UPDATE_USER	NVARCHAR(20)	NOT NULL,
	CONSTRAINT	PK_MENU	PRIMARY KEY(MENU_ID, TYPE)
)
GO
CREATE TABLE PRODUCT_MENU
(
	MENU_ID		CHAR(2)			NOT NULL,
	TYPE		VARCHAR(2)		NOT NULL,
	PRODUCT_ID	CHAR(10)		NOT NULL,
	DESCRITPION	NVARCHAR(500),
	VALID_FLAG	BIT				DEFAULT 1,
	ADD_USER	NVARCHAR(20)	NOT NULL,
	ADD_DATE	DATETIME		NOT NULL,
	UPDATE_USER	NVARCHAR(20)	NOT NULL,
	UPDATE_DATE	DATETIME		NOT NULL,
	CONSTRAINT	PK_PRODUCT_MENU	PRIMARY KEY(MENU_ID, TYPE, PRODUCT_ID)
)
GO
CREATE TABLE PRODUCT
(
	PRODUCT_ID		CHAR(10)		NOT NULL,
	PRODUCT_NAME	NVARCHAR(50)	NOT NULL,
	MADE_IN			NVARCHAR(20),
	QUANTITY		INT,
	TYPE			CHAR(1),
	UNIT1			NVARCHAR(10),	
	UNIT2			NVARCHAR(10),
	UNIT3			NVARCHAR(10),
	PRICE1			MONEY			NOT NULL DEFAULT 0,
	PRICE2			MONEY,
	PRICE3			MONEY,
	DISCOUNT1		INT,
	DISCOUNT2		INT,
	DISCOUNT3		INT,
	VAT1			MONEY,
	VAT2			MONEY,
	VAT3			MONEY,
	DESCRIPTION		NVARCHAR(500),
	IMAGE_URL		TEXT,
	VALID_FLAG		BIT				DEFAULT 1,
	ADD_USER		NVARCHAR(20)	NOT NULL,
	ADD_DATE		DATETIME		NOT NULL,
	UPDATE_USER		NVARCHAR(20)	NOT NULL,
	UPDATE_DATE		DATETIME		NOT NULL,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(PRODUCT_ID)
)
GO
CREATE TABLE ITEM_CODE
(
	CODE_ID		NVARCHAR(50)	NOT NULL,
	ITEM_ID		NVARCHAR(5)		NOT NULL,
	ITEM_NAME	NVARCHAR(50)	NOT NULL,
	VALID_FLAG	BIT				DEFAULT 1,
	ADD_USER	NVARCHAR(20)	NOT NULL,
	ADD_DATE	DATETIME		NOT NULL,
	UPDATE_USER	NVARCHAR(20)	NOT NULL,
	UPDATE_DATE	DATETIME		NOT NULL,
	CONSTRAINT	PK_ITEM_CODE PRIMARY KEY(CODE_ID)
)
GO
CREATE TABLE SLIDE
(
	SLIDE_ID		CHAR(5)			NOT NULL,
	DESCRIPTION		NVARCHAR(500),
	IMAGE_URL		TEXT,
	SLOGAN1			NVARCHAR(50),
	SLOGAN2			NVARCHAR(50),
	VALID_FLAG		BIT				DEFAULT 1,
	ADD_USER		NVARCHAR(20)	NOT NULL,
	ADD_DATE		DATETIME		NOT NULL,
	UPDATE_USER		NVARCHAR(20)	NOT NULL,
	UPDATE_DATE		DATETIME		NOT NULL,
	CONSTRAINT PK_SLIDE	PRIMARY KEY(SLIDE_ID)
)
GO
CREATE TABLE NEWS
(
	NEWS_ID		CHAR(5)			NOT NULL,
	--TAG_ID		CHAR(5),
	TITLE		NVARCHAR(50),
	SUMMARY		NVARCHAR(200),
	CONTENT		NVARCHAR(MAX),
	VALID_FLAG	BIT				DEFAULT 1,
	ADD_USER	NVARCHAR(20)	NOT NULL,
	ADD_DATE	DATETIME		NOT NULL,
	UPDATE_USER	NVARCHAR(20)	NOT NULL,
	UPDATE_DATE	DATETIME		NOT NULL,	
	CONSTRAINT	PK_NEWS	PRIMARY KEY(NEWS_ID)
)
--GO
--CREATE TABLE TAG
--(
--	TAG_ID		CHAR(5)			NOT NULL,
--	TAG_NAME	NVARCHAR(50),
--	DESCRIPTION	NVARCHAR(500),
--	VALID_FLAG	BIT				DEFAULT 1,
--	ADD_USER	NVARCHAR(20)	NOT NULL,
--	ADD_DATE	DATETIME		NOT NULL,
--	UPDATE_USER	NVARCHAR(20)	NOT NULL,
--	UPDATE_DATE	DATETIME		NOT NULL,
--	CONSTRAINT PK_TAG PRIMARY KEY(TAG_ID)
--)
GO
CREATE TABLE ROLE
(
	ROLE_ID				CHAR(5)			NOT NULL,
	TYPE				NVARCHAR(5)		NOT NULL,
	ROLE_NAME			NVARCHAR(50),
	READ_ONLY			BIT				DEFAULT 0,
	ENABLE_INSERT		BIT				DEFAULT 0,
	ENABLE_UPDATE		BIT				DEFAULT 0,
	ENABLE_DELETE		BIT				DEFAULT 0,
	DESCRIPTION			NVARCHAR(500),
	VALID_FLAG			BIT				DEFAULT 1,
	ADD_USER			NVARCHAR(20)	NOT NULL,
	ADD_DATE			DATETIME		NOT NULL,
	UPDATE_USER			NVARCHAR(20)	NOT NULL,
	UPDATE_DATE			DATETIME		NOT NULL,
	CONSTRAINT PK_ROLD PRIMARY KEY(ROLE_ID)
)
GO
CREATE TABLE ACCOUNT
(
	USER_ID			NVARCHAR(20)	NOT NULL,
	ROLE_ID			CHAR(5),
	PASSWORD		NVARCHAR(MAX),
	FIRST_NAME		NVARCHAR(50)	NOT NULL,
	LAST_NAME		NVARCHAR(50)	NOT NULL,
	ADDRESS			NVARCHAR(100),
	GENDER			BIT				DEFAULT 0,
	PHONE_NUMBER	VARCHAR(20),
	IDENTIFICATION	VARCHAR(30),
	AVATAR_URL		TEXT,
	VALID_FLAG		BIT				DEFAULT 1,
	ADD_USER		NVARCHAR(20)	NOT NULL,
	ADD_DATE		DATETIME		NOT NULL,
	UPDATE_USER		NVARCHAR(20)	NOT NULL,
	UPDATE_DATE		DATETIME		NOT NULL,
	CONSTRAINT	PK_USER	PRIMARY KEY(USER_ID)
)
