CREATE PROCEDURE p_SlideEntry
	@SLIDE_ID		CHAR(5),
	@DESCRIPTION	NVARCHAR(500),
	@IMAGE_URL		TEXT,
	@SLOGAN1		NVARCHAR(50),
	@SLOGAN2		NVARCHAR(50),
	@USER			NVARCHAR(20)
AS
BEGIN
	IF  NOT EXISTS(SELECT 1 FROM SLIDE WHERE SLIDE_ID = @SLIDE_ID)
			INSERT INTO SLIDE (
				SLIDE_ID,
				DESCRIPTION,
				IMAGE_URL,
				SLOGAN1,
				SLOGAN2,
				VALID_FLAG,
				ADD_USER,
				ADD_DATE,
				UPDATE_USER,
				UPDATE_DATE
			) VALUES (
				 (SELECT  DBO.F_FORMAT(ISNULL(MAX(CONVERT(INT, SLIDE_ID)) + 1, 1), 5, '0')
				 FROM SLIDE)
				,@DESCRIPTION
				,@IMAGE_URL
				,@SLOGAN1
				,@SLOGAN2
				,'1'
				,@USER
				,GETDATE()
				,@USER
				,GETDATE()
			);
	ELSE
		UPDATE SLIDE SET
			DESCRIPTION = @DESCRIPTION
			,IMAGE_URL = @IMAGE_URL
			,SLOGAN1 = @SLOGAN1
			,SLOGAN2 = @SLOGAN2
			,VALID_FLAG = '1'
			,ADD_USER = @USER
			,UPDATE_DATE = FORMAT(GETDATE(),'dd/MM/yyyy HH:mm')
		WHERE SLIDE_ID = @SLIDE_ID
			
	IF @@ROWCOUNT > 0
		SELECT ERR_CODE = 'SUCCESS';
	ELSE
		SELECT ERR_CODE = 'ERROR';
END
GO

ALTER PROCEDURE p_ProductEntry 
	@PRODUCT_ID		CHAR(10),		
	@PRODUCT_NAME	NVARCHAR(50),
	@PRICE1			MONEY,			
	@DESCRIPTION	NVARCHAR(500),
	@IMAGE_URL		TEXT,			
	@USER			NVARCHAR(20),
	@MENU_ID		CHAR(2)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_ID = @PRODUCT_ID) 
	BEGIN
			INSERT INTO PRODUCT (
				PRODUCT_ID,
				PRODUCT_NAME,
				PRICE1,
				DESCRIPTION,
				IMAGE_URL,
				VALID_FLAG,
				ADD_USER,
				ADD_DATE,
				UPDATE_USER,
				UPDATE_DATE
			) VALUES (
				(SELECT  DBO.F_FORMAT(ISNULL(MAX(CONVERT(INT, PRODUCT_ID)) + 1, 1), 10, '0')
				FROM PRODUCT),
				@PRODUCT_NAME,
				@PRICE1,
				@DESCRIPTION,
				@IMAGE_URL,
				'1',
				@USER,
				GETDATE(),
				@USER,
				GETDATE()
			);

			IF @@ROWCOUNT > 0
					INSERT INTO PRODUCT_MENU (
						MENU_ID,
						TYPE,	
						PRODUCT_ID,
						VALID_FLAG,
						ADD_USER,
						ADD_DATE,
						UPDATE_USER,
						UPDATE_DATE
					) VALUES (
						@MENU_ID,
						'2',
						(SELECT MAX(PRODUCT_ID) FROM PRODUCT),
						'1',
						@USER,
						GETDATE(),
						@USER,
						GETDATE()
					)
		END 
	ELSE 
		BEGIN
			UPDATE PRODUCT SET
				PRODUCT_NAME = @PRODUCT_NAME,
				PRICE1		 = @PRICE1,
				DESCRIPTION	 = @DESCRIPTION,
				IMAGE_URL	 = @IMAGE_URL,
				MENU		 = @MENU_ID,
				VALID_FLAG	 = '1',
				UPDATE_USER	 = @USER,
				UPDATE_DATE	 = GETDATE()
			WHERE	PRODUCT_ID = @PRODUCT_ID;
		
			UPDATE PRODUCT_MENU SET
				VALID_FLAG	 = '1',
				UPDATE_USER	 = @USER,
				UPDATE_DATE	 = GETDATE()
			WHERE	PRODUCT_ID	= @PRODUCT_ID
			AND		MENU_ID		= @MENU_ID
			AND		TYPE		= '2';
		END
	
	IF @@ROWCOUNT > 0
		SELECT ERR_CODE = 'SUCCESS';
	ELSE
		SELECT ERR_CODE = 'ERROR';
END
GO

ALTER PROCEDURE p_ProductDelete
	@PRODUCT_ID		CHAR(10),		
	@USER			NVARCHAR(20),
	@MENU_ID		CHAR(2)
AS
BEGIN
	UPDATE PRODUCT SET
		VALID_FLAG	 = '0',
		UPDATE_USER	 = @USER,
		UPDATE_DATE	 = GETDATE()
	WHERE	PRODUCT_ID = @PRODUCT_ID;
	
	--UPDATE PRODUCT_MENU SET
	--	VALID_FLAG	 = '0',
	--	UPDATE_USER	 = @USER,
	--	UPDATE_DATE	 = GETDATE()
	--WHERE	PRODUCT_ID	= @PRODUCT_ID
	--AND		MENU_ID		= @MENU_ID
	--AND		TYPE		= '2';

	IF @@ROWCOUNT > 0
		SELECT ERR_CODE = 'SUCCESS';
	ELSE
		SELECT ERR_CODE = 'ERROR';
END
GO

ALTER PROCEDURE P_ProductALL

AS
BEGIN
	DECLARE @V_SQL_QUERY NVARCHAR(MAX);
	SET @V_SQL_QUERY = '
						SELECT  PRODUCT_ID,
								PRODUCT_NAME,
								PRICE1,
								DESCRIPTION,
								IMAGE_URL
						FROM PRODUCT 
						WHERE VALID_FLAG = 1';
	EXEC(@V_SQL_QUERY);
 
END
GO

SELECT  PRODUCT_ID,
		PRODUCT_NAME,
		PRICE1,
		DESCRIPTION,
		IMAGE_URL
FROM PRODUCT 
WHERE VALID_FLAG = 0
